name: Deploy to HuggingFace

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Hugging Face CLI
      run: pip install "huggingface_hub[cli]"

    - name: Login to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: echo "$HF_TOKEN" | huggingface-cli login --token "$HF_TOKEN" --add-to-token-cache

    - name: Upload Repo to HuggingFace Space
      run: huggingface-cli upload . Ruturaj0077/product-recommendation-system --repo-type space
